### ISSUE TITLE
type 'double' is not a subtype of type 'int

### ISSUE THREAD

**Issue by bibash28** [jonasroussel/dart_jsonwebtoken#55] opened 2024-04-22 09:37 UTC
Syntax
```
JWT.verify(
        token,
        EdDSAPublicKey(x),
        checkHeaderType: false,
      );
```

token
`eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDp3ZWI6dGFsYW8uY28ja2V5LTQiLCJ0eXAiOiJvYXV0aC1hdXRoei1yZXErand0In0.eyJhdWQiOiJodHRwczovL3NlbGYtaXNzdWVkLm1lL3YyIiwiY2xpZW50X2lkIjoiZGlkOndlYjp0YWxhby5jbyIsImNsaWVudF9pZF9zY2hlbWUiOiJkaWQiLCJjbGllbnRfbWV0YWRhdGFfdXJpIjoiaHR0cHM6Ly90YWxhby5jby92ZXJpZmllci93YWxsZXQvY2xpZW50X21ldGFkYXRhX3VyaS9jZmppZWhobGtuIiwiZXhwIjoxNzEzNzc5MzEwLjYyMzQ2MiwiaXNzIjoiZGlkOndlYjp0YWxhby5jbyIsIm5vbmNlIjoiMjVjOWY5YjUtMDA4Yi0xMWVmLTg1MzUtMGExNjI4OTU4NTYwIiwicHJlc2VudGF0aW9uX2RlZmluaXRpb24iOnsiZm9ybWF0Ijp7Imp3dF92Y19qc29uIjp7ImFsZyI6WyJFUzI1NmsiLCJFUzI1NiIsIkVkRFNBIl19LCJqd3RfdnBfanNvbiI6eyJhbGciOlsiRVMyNTZrIiwiRVMyNTYiLCJFZERTQSJdfX0sImlkIjoiZDgxZmY4ZDItZmZlYS0xMWVlLThlMGQtMGExNjI4OTU4NTYwIiwiaW5wdXRfZGVzY3JpcHRvcnMiOlt7ImNvbnN0cmFpbnRzIjp7ImZpZWxkcyI6W3siZmlsdGVyIjp7InBhdHRlcm4iOiJFbWFpbFBhc3MiLCJ0eXBlIjoic3RyaW5nIn0sInBhdGgiOlsiJC5jcmVkZW50aWFsU3ViamVjdC50eXBlIl19XX0sImlkIjoiZW1haWxwYXNzXzEiLCJuYW1lIjoiSW5wdXQgZGVzY3JpcHRvciBmb3IgY3JlZGVudGlhbCAxIiwicHVycG9zZSI6IiJ9XSwibmFtZSI6IlRlc3QgIzE0IiwicHVycG9zZSI6IkFsdG1lIHByZXNlbnRhdGlvbiBkZWZpbml0aW9uIHN1YnNldCBvZiBQRVggdjIuMCJ9LCJyZXNwb25zZV9tb2RlIjoiZGlyZWN0X3Bvc3QiLCJyZXNwb25zZV90eXBlIjoidnBfdG9rZW4iLCJyZXNwb25zZV91cmkiOiJodHRwczovL3RhbGFvLmNvL3ZlcmlmaWVyL3dhbGxldC9lbmRwb2ludC8yNWM5ZDVjOC0wMDhiLTExZWYtYjVlZi0wYTE2Mjg5NTg1NjAiLCJzdGF0ZSI6IjI1YzlmYTllLTAwOGItMTFlZi1iM2Q5LTBhMTYyODk1ODU2MCJ9.zBlbg2TOQ3c9zk3iLIl4BOQ84QkFyObc4aaSNwPtTaMtUbgHyoW_8eqta9PImiyfFLMhyodpTlUWvMD5ljgyCQ`

key
`{"crv":"Ed25519","kty":"OKP","x":"FUoLewH4w4-KdaPH2cjZbL--CKYxQRWR05Yd_bIbhQo="}`

x 
`FUoLewH4w4-KdaPH2cjZbL--CKYxQRWR05Yd_bIbhQo=`

**Comment by jonasroussel** [comment] 2024-04-25 16:00
Ok, this is caused by the token payload. "exp" is a double, and I only convert int. Should be fixed in the next version
![Capture d’écran 2024-04-25 à 17 59 40](https://github.com/jonasroussel/dart_jsonwebtoken/assets/59713554/904a2fe5-d40c-4c55-a225-1d43a7abc84a)

**Comment by jonasroussel** [comment] 2024-04-25 16:19
Fixed in this version: https://pub.dev/packages/dart_jsonwebtoken/versions/2.14.0

**Closed by jonasroussel** 2024-04-25 16:19 UTC

**Comment by bibash28** [comment] 2024-04-26 10:23
Thank you. will check and let you know..
